### ISSUE TITLE
Can't get dashboard to display individual stats 

### ISSUE THREAD

**Issue by sgoldthorpe** [TheChrisTech/Storj-Exporter-dashboard#3]
Installed new exporters and dashboard and the stats seem to only come from my first storagenode.  Tried changing lots of things but cannot get the dashboard to work by importing dashboard 20677.

![2024-05-10_16-17](https://github.com/TheChrisTech/Storj-Exporter-dashboard/assets/5052843/8a2a3d3a-82db-4243-8de3-195b9bcef55b)

I changed my prometheus config to contain separate jobs (containing 'storj') per storagenode by no joy:
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'storjnode01'
    static_configs:
      - targets: ["10.X.X.101:9651"]
  - job_name: 'storjnode02'
    static_configs:
      - targets: ["10.X.X.102:9651"]
  - job_name: 'storjnode03'
    static_configs:
      - targets: ["10.X.X.103:9651"]
  - job_name: 'storjnode04'
    static_configs:
      - targets: ["10.X.X.104:9651"]
  - job_name: 'storjnode05'
    static_configs:
      - targets: ["10.X.X.105:9651"]
  - job_name: 'storjnode06'
    static_configs:
      - targets: ["10.X.X.106:9651"]
```
I suspect I may be doing something silly.
